# Generated by Django 3.0.6 on 2020-05-12 14:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eggs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layed', models.IntegerField(default=0)),
                ('broken', models.IntegerField(default=0)),
                ('pecked', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Eggs',
                'verbose_name_plural': 'Eggss',
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('chickens', models.IntegerField(default=0)),
                ('rooster', models.IntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
            options={
                'verbose_name': 'Farm',
                'verbose_name_plural': 'Farms',
            },
        ),
    ]
