# Generated by Django 3.0.6 on 2020-05-16 11:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('huevos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EggsCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layed', models.IntegerField(default=0)),
                ('broken', models.IntegerField(default=0)),
                ('pecked', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='huevos.Farm', unique=True)),
            ],
            options={
                'verbose_name': 'EggsCount',
            },
        ),
        migrations.CreateModel(
            name='FoodCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used', models.FloatField(default=0.0, verbose_name='Verbrauch')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='huevos.Farm', unique=True)),
            ],
            options={
                'verbose_name': 'FoodCount',
                'verbose_name_plural': 'FoodCounts',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold', models.IntegerField(default=0, verbose_name='Verkaufter Eier')),
                ('used', models.IntegerField(default=0, verbose_name='Gebrauchter Eier')),
                ('price', models.FloatField(default=0.3, verbose_name='Eier Preise')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='huevos.Farm', unique=True)),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0.0, verbose_name='Lagerstand')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('price', models.FloatField(default=3.0, verbose_name='Eier Preise')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='huevos.Farm')),
            ],
            options={
                'verbose_name': 'Storage',
                'verbose_name_plural': 'Storages',
            },
        ),
        migrations.DeleteModel(
            name='Eggs',
        ),
        migrations.AddField(
            model_name='foodcount',
            name='stroage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='huevos.Storage', unique=True),
        ),
    ]
