# Generated by Django 3.0.6 on 2020-05-20 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('huevos', '0002_auto_20200516_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggscount',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='huevos.Farm'),
        ),
        migrations.AlterField(
            model_name='foodcount',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='huevos.Farm'),
        ),
        migrations.AlterField(
            model_name='foodcount',
            name='stroage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='huevos.Storage'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='huevos.Farm'),
        ),
    ]
